# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment/payment.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'payment/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from payment import payment_state_pb2 as payment_dot_payment__state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment/payment.proto\x12\x07payment\x1a\x1bpayment/payment_state.proto\"v\n\x0ePaymentDetails\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x0f\n\x07nominal\x18\x04 \x01(\t\x12$\n\x05state\x18\x05 \x01(\x0e\x32\x15.payment.PaymentState\"\x19\n\x06UserID\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x17\n\tPaymentID\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\x0bPaymentList\x12)\n\x08payments\x18\x01 \x03(\x0b\x32\x17.payment.PaymentDetails\" \n\x0eUnpaidSessions\x12\x0e\n\x06unpaid\x18\x01 \x01(\x08\x32\xc4\x02\n\x07Payment\x12\x41\n\rCreatePayment\x12\x17.payment.PaymentDetails\x1a\x17.payment.PaymentDetails\x12\x41\n\rUpdatePayment\x12\x17.payment.PaymentDetails\x1a\x17.payment.PaymentDetails\x12\x34\n\x0bGetPayments\x12\x0f.payment.UserID\x1a\x14.payment.PaymentList\x12\x39\n\nGetPayment\x12\x12.payment.PaymentID\x1a\x17.payment.PaymentDetails\x12\x42\n\x11GetUnpaidPayments\x12\x17.payment.UnpaidSessions\x1a\x14.payment.PaymentListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTDETAILS']._serialized_start=63
  _globals['_PAYMENTDETAILS']._serialized_end=181
  _globals['_USERID']._serialized_start=183
  _globals['_USERID']._serialized_end=208
  _globals['_PAYMENTID']._serialized_start=210
  _globals['_PAYMENTID']._serialized_end=233
  _globals['_PAYMENTLIST']._serialized_start=235
  _globals['_PAYMENTLIST']._serialized_end=291
  _globals['_UNPAIDSESSIONS']._serialized_start=293
  _globals['_UNPAIDSESSIONS']._serialized_end=325
  _globals['_PAYMENT']._serialized_start=328
  _globals['_PAYMENT']._serialized_end=652
# @@protoc_insertion_point(module_scope)
