# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from payment import payment_pb2 as payment_dot_payment__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payment/payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePayment = channel.unary_unary(
                '/payment.Payment/CreatePayment',
                request_serializer=payment_dot_payment__pb2.PaymentDetails.SerializeToString,
                response_deserializer=payment_dot_payment__pb2.PaymentDetails.FromString,
                _registered_method=True)
        self.UpdatePayment = channel.unary_unary(
                '/payment.Payment/UpdatePayment',
                request_serializer=payment_dot_payment__pb2.PaymentDetails.SerializeToString,
                response_deserializer=payment_dot_payment__pb2.PaymentDetails.FromString,
                _registered_method=True)
        self.GetPayments = channel.unary_unary(
                '/payment.Payment/GetPayments',
                request_serializer=payment_dot_payment__pb2.UserID.SerializeToString,
                response_deserializer=payment_dot_payment__pb2.PaymentList.FromString,
                _registered_method=True)
        self.GetPayment = channel.unary_unary(
                '/payment.Payment/GetPayment',
                request_serializer=payment_dot_payment__pb2.PaymentID.SerializeToString,
                response_deserializer=payment_dot_payment__pb2.PaymentDetails.FromString,
                _registered_method=True)
        self.GetUnpaidPayments = channel.unary_unary(
                '/payment.Payment/GetUnpaidPayments',
                request_serializer=payment_dot_payment__pb2.UnpaidSessions.SerializeToString,
                response_deserializer=payment_dot_payment__pb2.PaymentList.FromString,
                _registered_method=True)


class PaymentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnpaidPayments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePayment,
                    request_deserializer=payment_dot_payment__pb2.PaymentDetails.FromString,
                    response_serializer=payment_dot_payment__pb2.PaymentDetails.SerializeToString,
            ),
            'UpdatePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePayment,
                    request_deserializer=payment_dot_payment__pb2.PaymentDetails.FromString,
                    response_serializer=payment_dot_payment__pb2.PaymentDetails.SerializeToString,
            ),
            'GetPayments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayments,
                    request_deserializer=payment_dot_payment__pb2.UserID.FromString,
                    response_serializer=payment_dot_payment__pb2.PaymentList.SerializeToString,
            ),
            'GetPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayment,
                    request_deserializer=payment_dot_payment__pb2.PaymentID.FromString,
                    response_serializer=payment_dot_payment__pb2.PaymentDetails.SerializeToString,
            ),
            'GetUnpaidPayments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnpaidPayments,
                    request_deserializer=payment_dot_payment__pb2.UnpaidSessions.FromString,
                    response_serializer=payment_dot_payment__pb2.PaymentList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.Payment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.Payment', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Payment(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.Payment/CreatePayment',
            payment_dot_payment__pb2.PaymentDetails.SerializeToString,
            payment_dot_payment__pb2.PaymentDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.Payment/UpdatePayment',
            payment_dot_payment__pb2.PaymentDetails.SerializeToString,
            payment_dot_payment__pb2.PaymentDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPayments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.Payment/GetPayments',
            payment_dot_payment__pb2.UserID.SerializeToString,
            payment_dot_payment__pb2.PaymentList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.Payment/GetPayment',
            payment_dot_payment__pb2.PaymentID.SerializeToString,
            payment_dot_payment__pb2.PaymentDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnpaidPayments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.Payment/GetUnpaidPayments',
            payment_dot_payment__pb2.UnpaidSessions.SerializeToString,
            payment_dot_payment__pb2.PaymentList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
