services:
  Backend:
    build:
      dockerfile: Dockerfile
    image: thd/frontend_api
    container_name: THD_Frontend_API
    hostname: THD_Frontend_API
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - DB_MANAGER_PORT = 50051
      - DB_Manager = THD_DB_Manager
      - MONGO_MANAGER_PORT = 50051
      - MONGO_MANAGER = THD_Mongo_Manager
    depends_on:
      DBManager:
        condition: service_started
      Mongo_Manager:
        condition: service_started

  Postgres:
    build: https://github.com/THD-C/Postgres.git
    image: thd/postgres
    container_name: THD_Postgres
    hostname: Postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - PG-Data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U default -d thdc" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  DBManager:
    build: https://github.com/THD-C/DB_Manager.git
    image: thd/dbmanager
    container_name: THD_DB_Manager
    hostname: THD_DB_Manager
    restart: unless-stopped
    ports:
      - 50051:50051
    environment:
      - POSTGRES_URL=postgresql://default:PL_tech_hand_elk@Postgres:5432/thdc
      - DROP_EXISTING_DB=True
    depends_on:
      Postgres:
        condition: service_healthy

  Mongo:
    build:
      context: https://github.com/THD-C/Mongo.git
      secrets:
        - github_token
    image: thd/mongo
    container_name: THD_Mongo
    hostname: Mongo
    restart: unless-stopped
    depends_on:
      DBManager:
        condition: service_started
    ports:
      - 27017:27017
    volumes:
      - MO-Data:/data/db

  Mongo_Manager:
    build: https://github.com/THD-C/Mongo_Manager.git
    image: thd/mongo_manager
    container_name: THD_Mongo_Manager
    hostname: THD_Mongo_Manager
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://Mongo/THDC
    ports:
      - 50052:50051
    depends_on:
      Mongo:
        condition: service_started

secrets:
  github_token:
    file: ./.github_token
volumes:
  PG-Data:
  MO-Data: