# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wallet/wallet.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'wallet/wallet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from user import user_detail_pb2 as user_dot_user__detail__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13wallet/wallet.proto\x12\x06wallet\x1a\x16user/user_detail.proto\"F\n\x06Wallet\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\"-\n\nWalletList\x12\x1f\n\x07wallets\x18\x01 \x03(\x0b\x32\x0e.wallet.Wallet2\xa2\x01\n\x07Wallets\x12.\n\x0c\x63reateWallet\x12\x0e.wallet.Wallet\x1a\x0e.wallet.Wallet\x12.\n\x0cupdateWallet\x12\x0e.wallet.Wallet\x1a\x0e.wallet.Wallet\x12\x37\n\x0fgetUsersWallets\x12\x10.user.UserDetail\x1a\x12.wallet.WalletListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wallet.wallet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WALLET']._serialized_start=55
  _globals['_WALLET']._serialized_end=125
  _globals['_WALLETLIST']._serialized_start=127
  _globals['_WALLETLIST']._serialized_end=172
  _globals['_WALLETS']._serialized_start=175
  _globals['_WALLETS']._serialized_end=337
# @@protoc_insertion_point(module_scope)
