# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from wallet import wallet_pb2 as wallet_dot_wallet__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in wallet/wallet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WalletsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWallet = channel.unary_unary(
                '/wallet.Wallets/CreateWallet',
                request_serializer=wallet_dot_wallet__pb2.Wallet.SerializeToString,
                response_deserializer=wallet_dot_wallet__pb2.Wallet.FromString,
                _registered_method=True)
        self.UpdateWallet = channel.unary_unary(
                '/wallet.Wallets/UpdateWallet',
                request_serializer=wallet_dot_wallet__pb2.Wallet.SerializeToString,
                response_deserializer=wallet_dot_wallet__pb2.Wallet.FromString,
                _registered_method=True)
        self.DeleteWallet = channel.unary_unary(
                '/wallet.Wallets/DeleteWallet',
                request_serializer=wallet_dot_wallet__pb2.WalletID.SerializeToString,
                response_deserializer=wallet_dot_wallet__pb2.Wallet.FromString,
                _registered_method=True)
        self.GetWallet = channel.unary_unary(
                '/wallet.Wallets/GetWallet',
                request_serializer=wallet_dot_wallet__pb2.WalletID.SerializeToString,
                response_deserializer=wallet_dot_wallet__pb2.Wallet.FromString,
                _registered_method=True)
        self.GetUsersWallets = channel.unary_unary(
                '/wallet.Wallets/GetUsersWallets',
                request_serializer=wallet_dot_wallet__pb2.UserID.SerializeToString,
                response_deserializer=wallet_dot_wallet__pb2.WalletList.FromString,
                _registered_method=True)


class WalletsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersWallets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWallet,
                    request_deserializer=wallet_dot_wallet__pb2.Wallet.FromString,
                    response_serializer=wallet_dot_wallet__pb2.Wallet.SerializeToString,
            ),
            'UpdateWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWallet,
                    request_deserializer=wallet_dot_wallet__pb2.Wallet.FromString,
                    response_serializer=wallet_dot_wallet__pb2.Wallet.SerializeToString,
            ),
            'DeleteWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWallet,
                    request_deserializer=wallet_dot_wallet__pb2.WalletID.FromString,
                    response_serializer=wallet_dot_wallet__pb2.Wallet.SerializeToString,
            ),
            'GetWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWallet,
                    request_deserializer=wallet_dot_wallet__pb2.WalletID.FromString,
                    response_serializer=wallet_dot_wallet__pb2.Wallet.SerializeToString,
            ),
            'GetUsersWallets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersWallets,
                    request_deserializer=wallet_dot_wallet__pb2.UserID.FromString,
                    response_serializer=wallet_dot_wallet__pb2.WalletList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wallet.Wallets', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wallet.Wallets', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Wallets(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.Wallets/CreateWallet',
            wallet_dot_wallet__pb2.Wallet.SerializeToString,
            wallet_dot_wallet__pb2.Wallet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.Wallets/UpdateWallet',
            wallet_dot_wallet__pb2.Wallet.SerializeToString,
            wallet_dot_wallet__pb2.Wallet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.Wallets/DeleteWallet',
            wallet_dot_wallet__pb2.WalletID.SerializeToString,
            wallet_dot_wallet__pb2.Wallet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.Wallets/GetWallet',
            wallet_dot_wallet__pb2.WalletID.SerializeToString,
            wallet_dot_wallet__pb2.Wallet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsersWallets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.Wallets/GetUsersWallets',
            wallet_dot_wallet__pb2.UserID.SerializeToString,
            wallet_dot_wallet__pb2.WalletList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
