# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from secret import secret_pb2 as secret_dot_secret__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in secret/secret_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SecretStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSecret = channel.unary_unary(
                '/secret.SecretStore/GetSecret',
                request_serializer=secret_dot_secret__pb2.SecretName.SerializeToString,
                response_deserializer=secret_dot_secret__pb2.SecretValue.FromString,
                _registered_method=True)


class SecretStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecretStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecret,
                    request_deserializer=secret_dot_secret__pb2.SecretName.FromString,
                    response_serializer=secret_dot_secret__pb2.SecretValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'secret.SecretStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('secret.SecretStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecretStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/secret.SecretStore/GetSecret',
            secret_dot_secret__pb2.SecretName.SerializeToString,
            secret_dot_secret__pb2.SecretValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
