# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from coins import coins_pb2 as coins_dot_coins__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in coins/coins_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoinsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCoinData = channel.unary_unary(
                '/coins.Coins/GetCoinData',
                request_serializer=coins_dot_coins__pb2.CoinDataRequest.SerializeToString,
                response_deserializer=coins_dot_coins__pb2.DataResponse.FromString,
                _registered_method=True)
        self.GetHistoricalData = channel.unary_unary(
                '/coins.Coins/GetHistoricalData',
                request_serializer=coins_dot_coins__pb2.HistoricalDataRequest.SerializeToString,
                response_deserializer=coins_dot_coins__pb2.DataResponse.FromString,
                _registered_method=True)


class CoinsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCoinData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoinsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCoinData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoinData,
                    request_deserializer=coins_dot_coins__pb2.CoinDataRequest.FromString,
                    response_serializer=coins_dot_coins__pb2.DataResponse.SerializeToString,
            ),
            'GetHistoricalData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoricalData,
                    request_deserializer=coins_dot_coins__pb2.HistoricalDataRequest.FromString,
                    response_serializer=coins_dot_coins__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coins.Coins', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coins.Coins', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coins(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCoinData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coins.Coins/GetCoinData',
            coins_dot_coins__pb2.CoinDataRequest.SerializeToString,
            coins_dot_coins__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoricalData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coins.Coins/GetHistoricalData',
            coins_dot_coins__pb2.HistoricalDataRequest.SerializeToString,
            coins_dot_coins__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
