# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coins/coins.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'coins/coins.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oins/coins.proto\x12\x05\x63oins\"\"\n\x0f\x43oinDataRequest\x12\x0f\n\x07\x63oin_id\x18\x01 \x01(\t\"N\n\x15HistoricalDataRequest\x12\x0f\n\x07\x63oin_id\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\"C\n\x0c\x44\x61taResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2\x8b\x01\n\x05\x43oins\x12:\n\x0bGetCoinData\x12\x16.coins.CoinDataRequest\x1a\x13.coins.DataResponse\x12\x46\n\x11GetHistoricalData\x12\x1c.coins.HistoricalDataRequest\x1a\x13.coins.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coins.coins_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COINDATAREQUEST']._serialized_start=28
  _globals['_COINDATAREQUEST']._serialized_end=62
  _globals['_HISTORICALDATAREQUEST']._serialized_start=64
  _globals['_HISTORICALDATAREQUEST']._serialized_end=142
  _globals['_DATARESPONSE']._serialized_start=144
  _globals['_DATARESPONSE']._serialized_end=211
  _globals['_COINS']._serialized_start=214
  _globals['_COINS']._serialized_end=353
# @@protoc_insertion_point(module_scope)
