name: Run Python Test

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**/*.py"
      - requirements.txt
  workflow_dispatch:

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  Test:
    uses: THD-C/GH_Actions/.github/workflows/run-tests.yml@main